/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { WeatherService } from "../weather.service";
import { WeatherCreateInput } from "./WeatherCreateInput";
import { Weather } from "./Weather";
import { WeatherFindManyArgs } from "./WeatherFindManyArgs";
import { WeatherWhereUniqueInput } from "./WeatherWhereUniqueInput";
import { WeatherUpdateInput } from "./WeatherUpdateInput";

export class WeatherControllerBase {
  constructor(protected readonly service: WeatherService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Weather })
  async createWeather(
    @common.Body() data: WeatherCreateInput
  ): Promise<Weather> {
    return await this.service.createWeather({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Weather] })
  @ApiNestedQuery(WeatherFindManyArgs)
  async weathers(@common.Req() request: Request): Promise<Weather[]> {
    const args = plainToClass(WeatherFindManyArgs, request.query);
    return this.service.weathers({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Weather })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async weather(
    @common.Param() params: WeatherWhereUniqueInput
  ): Promise<Weather | null> {
    const result = await this.service.weather({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Weather })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateWeather(
    @common.Param() params: WeatherWhereUniqueInput,
    @common.Body() data: WeatherUpdateInput
  ): Promise<Weather | null> {
    try {
      return await this.service.updateWeather({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Weather })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteWeather(
    @common.Param() params: WeatherWhereUniqueInput
  ): Promise<Weather | null> {
    try {
      return await this.service.deleteWeather({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
