/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Weather } from "./Weather";
import { WeatherCountArgs } from "./WeatherCountArgs";
import { WeatherFindManyArgs } from "./WeatherFindManyArgs";
import { WeatherFindUniqueArgs } from "./WeatherFindUniqueArgs";
import { DeleteWeatherArgs } from "./DeleteWeatherArgs";
import { WeatherService } from "../weather.service";
@graphql.Resolver(() => Weather)
export class WeatherResolverBase {
  constructor(protected readonly service: WeatherService) {}

  async _weathersMeta(
    @graphql.Args() args: WeatherCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Weather])
  async weathers(
    @graphql.Args() args: WeatherFindManyArgs
  ): Promise<Weather[]> {
    return this.service.weathers(args);
  }

  @graphql.Query(() => Weather, { nullable: true })
  async weather(
    @graphql.Args() args: WeatherFindUniqueArgs
  ): Promise<Weather | null> {
    const result = await this.service.weather(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Weather)
  async deleteWeather(
    @graphql.Args() args: DeleteWeatherArgs
  ): Promise<Weather | null> {
    try {
      return await this.service.deleteWeather(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
